# This file should be generated by the ./configure script
CC=ccache gcc
WITH_GPL=1

HAVE_PKGCONFIG=1
USE_CS4=0
USE_CSNEXT=0
DESTDIR=
PREFIX=/usr/local
BINDIR=/usr/local/bin
LIBDIR=/usr/local/lib
MANDIR=/usr/local/share/man
DOCDIR=/usr/local/share/doc/radare2
DATADIR=/usr/local/share
INCLUDEDIR=/usr/local/include

R2_USE_SQSH=0
SQSH_CFLAGS=
SQSH_LDFLAGS=

HAVE_LIB_GMP=0
USE_RPATH=1
HAVE_JEMALLOC=1
HAVE_FORK=1
WANT_DYLINK=1
WANT_CAPSTONE=1
WITH_STATIC_THEMES=0
WITH_LIBR=0
NEW_IO_CACHE=@NEW_IO_CACHE@

ifeq ($(USE_RPATH),1)
LDFLAGS_RPATH=-Wl,-rpath,"${LIBDIR}"
else
LDFLAGS_RPATH=
endif

MKPLUGINS=mk/stat.mk mk/sloc.mk

USERCC=gcc
COMPILER0=$(shell echo "${USERCC}" | awk '{print $$1}')
COMPILER=$(shell basename ${COMPILER0})
DEBUGGER=1

INSTALL_DIR=/usr/bin/install -d
INSTALL_DATA=/usr/bin/install -m 644
INSTALL_PROGRAM=/usr/bin/install -m 755
INSTALL_SCRIPT=/usr/bin/install -m 755
INSTALL_MAN=/usr/bin/install -m 444
INSTALL_LIB=/usr/bin/install -m 755 -c

VERSION=5.9.9
R2_VERSION=5.9.9
R2_VERSION_MAJOR=5
R2_VERSION_MINOR=9
R2_VERSION_PATCH=9
R2_VERSION_NUMBER=50909
LIBVERSION=5.9.9
ABIVERSION=$(shell echo 5.9.9 | awk -F . '{print $$1"."$$2}')

# ./configure --with-ostype=[linux,osx,solaris,windows] # TODO: rename to w32, w64?
OSTYPE=gnulinux
BUILD_OS=linux
HOST_OS=linux
ifeq ($(WANT_DYLINK),1)

# workaround: must be fixed in acr
ifeq ($(OSTYPE),qnx)
DL_LIBS=
else
ifeq ($(OSTYPE),windows)
else
ifeq ($(OSTYPE),darwin)
else
DL_LIBS=-ldl
endif
endif
endif

else
# WANT_DYLINK=0
DL_LIBS=
endif

# capstone
ifeq ($(WANT_CAPSTONE),1)
USE_CAPSTONE=0
else
USE_CAPSTONE=0
endif
ifeq ($(USE_CAPSTONE),1)
CAPSTONE_CFLAGS=$(subst include/capstone,include,)
CAPSTONE_LDFLAGS=
else
CAPSTONE_CFLAGS=
CAPSTONE_LDFLAGS=
endif

HAVE_LIB_GMP=0
HAVE_LIB_SSL=0
WANT_SSL_CRYPTO=0
HAVE_LIB_MAGIC=0
USE_LIB_MAGIC=0
HAVE_LIB_XXHASH=0
USE_LIB_XXHASH=0
USE_LIB_ZIP=0
LIBMAGIC=
LIBZIP=
LIBXXHASH=

USE_SYSLZ4=0
USE_SMALLZ4=@USE_SMALLZ4@

ifeq ($(USE_SYSLZ4),1)
LZ4_LDFLAGS=
LZ4_CFLAGS=
endif

ifeq ($(HAVE_LIB_SSL),1)
SSL_CFLAGS=
SSL_LDFLAGS=
endif

HAVE_LIBUV=0
LIBUV_CFLAGS=
LIBUV_LDFLAGS=

HAVE_GPERF=0

HAVE_PTRACE=1
USE_PTRACE_WRAP=1

CLOCK_LDFLAGS+=

# cache compiler flags at configure time #
CFLAGS+=
LDFLAGS+=-Wl,--as-needed
